# Generated by Django 3.2.9 on 2021-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('start_date', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=150)),
                ('total_vacancy', models.CharField(max_length=150)),
                ('total_price', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
            ],
        ),
    ]
